AWSTemplateFormatVersion: 2010-09-09
Description: 'RDS - aurora postgresql'
###############################################################################
Metadata:
###############################################################################

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Stack dependencies configuration"
        Parameters:
          - RDSClusterStack
      -
        Label:
          default: "Global configuration"
        Parameters:
          - GlobalName
      -
        Label:
          default: "RDS configuration"
        Parameters:
          - RDSInstanceSubName
          - RDSEngineType
          - RDSEngineVersion
          - RDSInstanceType
      -
        Label:
          default: "RDS parameter group configuration"
        Parameters:
          - RDSParameterGroupFamily
      -
        Label:
          default: "DNS configuration"
        Parameters:
          - DomainName
    ParameterLabels:
      RDSClusterstack:
        default: "Name of the RDS cluster's stack"
      GlobalName:
        default: "Client name"
      RDSInstanceSubName:
        default: "Name suffix"
      RDSEngineType:
        default: "Engine type"
      RDSEngineVersion:
        default: "Engine version"
      RDSInstanceType:
        default: "Instance type"
      RDSParameterGroupFamily:
        default: "Parameter group family"
      DomainName:
        default: "Domain name"
      RDSClusterStack:
        default: "RDS cluster stack"

###############################################################################
Parameters:
###############################################################################

  GlobalName:
    Description: 'Project GlobalName'
    Type: String
    Default: "robindabird"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSInstanceSubName:
    Description: "Rds Name (example for RDSInstanceSubName = '-slave'  : robindabird-rds-aurora-postgresql-slave)"
    Type: String

  RDSInstanceType:
    Type: String
    Default: db.r4.large
    AllowedValues:
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
    Description: 'Instance Size'

  RDSEngineType:
    Description: "RDS engine"
    Type: "String"
    Default: "aurora-postgresql"
    AllowedValues:
      #- "aurora-mysql" #(for MySQL 5.7-compatible Aurora)
      - "aurora-postgresql"

  RDSEngineVersion:
    Description: "RDS engine version"
    Type: "String"
    Default: "10.6"
    AllowedValues:
      # aurora-postgresql
      - "10.6"
      - "10.5"
      - "10.4"
      - "9.6.9"
      - "9.6.8"

  RDSParameterGroupFamily:
    Description: "RDS engine version"
    Type: "String"
    Default: "aurora-postgresql10"
    AllowedValues:
      # aurora-postgresql
      - "aurora-postgresql10"
      - "aurora-postgresql9.6"

  DomainName:
    Description: 'DomainName'
    Type: String
    Default: "robindabird"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSClusterStack:
      Description: "Name of the RDS cluster's stack"
      Type: String
      AllowedPattern : ".*"

###############################################################################
Resources:
###############################################################################

  RDSPAREMETERGROUP:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "RDS parameter group"
      Family: !Ref RDSParameterGroupFamily
      Parameters:
        application_name: ""

  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
#      AllocatedStorage: ""
      AllowMajorVersionUpgrade: "false"     # optional
      AutoMinorVersionUpgrade: "true"     # optional
#      BackupRetentionPeriod: "35"     # optional
      CopyTagsToSnapshot: "false"     # optional
      DBClusterIdentifier:
        Fn::ImportValue:
          !Sub "${RDSClusterStack}-RDSClusterIdentifier" # optional
      DBInstanceClass: !Ref RDSInstanceType     # required
      DBInstanceIdentifier: !Sub ${GlobalName}-rds-${RDSEngineType}${RDSInstanceSubName}
#        DBName: !Sub ${GlobalName}     # optional
      DBParameterGroupName: !Ref RDSPAREMETERGROUP     # optional
#      DBSecurityGroups: !Ref ClusterSecurityGroup               # optional, list of String
      DBSubnetGroupName:
        Fn::ImportValue:
          !Sub "${RDSClusterStack}-RDSSubnetGroupName" # optional
      Engine: !Ref RDSEngineType     # optional
      EngineVersion: !Ref RDSEngineVersion     # optional
#      KmsKeyId: String     # optional
#     MasterUsername:  "postgres"      # optional
#      MasterUserPassword: !Ref PostgresUserPassword     # optional
#      MonitoringInterval: Integer     # optional
#      MonitoringRoleArn: !Ref RDSMonitoringRole     # optional
      MultiAZ: "false"     # optional
#      OptionGroupName: String     # optional
#      Port: !Ref DBPort     # optional
#      PreferredBackupWindow: String     # optional
#      PreferredMaintenanceWindow: "Mon:01:00-Mon:01:30"     # optional
      PubliclyAccessible: "false"     # optional

  RDSDNS:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneName: !Sub '${DomainName}.local.'
      Comment: CNAME targeted to RDS.
      RecordSets:
        - Name: !Sub '${RDS}.${DomainName}.local.'
          Type: CNAME
          TTL: '900'
          ResourceRecords:
            - !GetAtt 'RDS.Endpoint.Address'
