AWSTemplateFormatVersion: 2010-09-09
Description: 'RDS - Cluster aurora postgresql'
###############################################################################
Metadata:
###############################################################################

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Global configuration"
        Parameters:
          - GlobalName
      -
        Label:
          default: "RDS cluster configuration"
        Parameters:
          - RDSClusterDefaultDatabase
          - RDSClusterPort
          - RDSClusterSuperUserName
          - RDSClusterSuperUserPassword
          - RDSClusterSubnets
          - RDSClusterSecurityGroup
          - RDSClusterEngineType
          - RDSClusterEngineVersion
      -
        Label:
          default: "RDS cluster parameter group configuration"
        Parameters:
          - RDSClusterParameterGroupFamily
      -
        Label:
          default: "DNS configuration"
        Parameters:
          - DomainName
    ParameterLabels:
      GlobalName:
        default: "Client name"
      RDSClusterDefaultDatabase:
        default: "Default database"
      RDSClusterPort:
        default: "Port number"
      RDSClusterSuperUserName:
        default: "Super user name"
      RDSClusterSuperUserPassword:
        default: "Super user password"
      RDSClusterSubnets:
        default: "Subnets"
      RDSClusterSecurityGroup:
        default: "Security group"
      RDSClusterEngineType:
        default: "Engine type"
      RDSClusterEngineVersion:
        default: "Engine version"
      RDSClusterParameterGroupFamily:
        default: "Parameter group family"
      DomainName:
        default: "Domain name"

###############################################################################
Parameters:
###############################################################################

  GlobalName:
    Description: 'Project GlobalName'
    Type: String
    Default: "robindabird"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSClusterDefaultDatabase:
    Description: "Default database"
    Type: String
    Default: "robindabird"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSClusterPort:
    Description: "RDS Network Port"
    Type: String
    Default: "5432"
    AllowedPattern : "[0-9]+"

  RDSClusterSuperUserPassword:
    Description: 'Super user password'
    Type: String
    NoEcho: "true"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSClusterSuperUserName:
    Description: 'Super user name'
    Type: String
    AllowedPattern : "[a-zA-Z0-9]+"
    default: "postgres"

  RDSClusterSubnets:
    Description: 'DB Subnets'
    Type: List<AWS::EC2::Subnet::Id>

  RDSClusterSecurityGroup:
    Description : "Database security group"
    Type: List<AWS::EC2::SecurityGroup::Id>

  RDSClusterEngineType:
    Description: "RDS engine"
    Type: "String"
    Default: "aurora-postgresql"
    AllowedValues:
      #- "aurora-mysql" #(for MySQL 5.7-compatible Aurora)
      - "aurora-postgresql"

  RDSClusterEngineVersion:
    Description: "RDS engine version"
    Type: "String"
    Default: "10.6"
    AllowedValues:
      # aurora-postgresql
      - "10.6"
      - "10.5"
      - "10.4"
      - "9.6.9"
      - "9.6.8"

  DomainName:
    Description: 'DomainName'
    Type: String
    Default: "robindabird"
    AllowedPattern : "[a-zA-Z0-9]+"

  RDSClusterParameterGroupFamily:
    Description: "RDS engine version"
    Type: "String"
    Default: "aurora-postgresql10"
    AllowedValues:
      # aurora-postgresql
      - "aurora-postgresql10"
      - "aurora-postgresql9.6"

###############################################################################
Resources:
###############################################################################
  RDSSUBNETGROUP:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${GlobalName}-rds-sub     # required
      SubnetIds: !Ref RDSClusterSubnets               # required, list of String
      Tags:                # optional, list of Tag
        - Key: "Name"
          Value: !Sub ${GlobalName}-rds-subnet-group

  RDSCLUSTERPARAMETERGROUP:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: "Cluster parameter group"     # required
      Family: !Ref RDSClusterParameterGroupFamily     # required
      Parameters:
        application_name: ""     # required

  RDSCLUSTER:
    Type: "AWS::RDS::DBCluster"
    Properties:
      #AvailabilityZones:
      #  - String
      #BacktrackWindow: Integer
      BackupRetentionPeriod: "35"
      DatabaseName: !Ref RDSClusterDefaultDatabase
      DBClusterIdentifier: !Sub ${GlobalName}-rds-cluster-${RDSClusterEngineType}
      DBClusterParameterGroupName: !Ref RDSCLUSTERPARAMETERGROUP
      DBSubnetGroupName: !Ref RDSSUBNETGROUP
      DeletionProtection: "false"
#      EnableCloudwatchLogsExports:
#        - String
      EnableIAMDatabaseAuthentication: "false"
      Engine: !Ref RDSClusterEngineType
      EngineMode: "provisioned"
      EngineVersion: !Ref RDSClusterEngineVersion
#      KmsKeyId: String
      MasterUsername: !Ref RDSClusterSuperUserName
      MasterUserPassword: !Ref RDSClusterSuperUserPassword
      Port: !Ref RDSClusterPort
#      PreferredBackupWindow: "hh24:mi-hh24:mi"
      PreferredMaintenanceWindow: "Mon:01:00-Mon:01:30"
      StorageEncrypted: "false"
#      Tags:
#        - Resource Tag
      VpcSecurityGroupIds: !Ref RDSClusterSecurityGroup               # optional, list of String

  RDSClusterDNSWriter:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneName: !Sub '${DomainName}.local.'
      Comment: CNAME targeted to RDS Cluster.
      RecordSets:
        - Name: !Sub '${RDSCLUSTER}-writer.${DomainName}.local.'
          Type: CNAME
          TTL: '900'
          ResourceRecords:
            - !GetAtt 'RDSCLUSTER.Endpoint.Address'

  RDSClusterDNSReader:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneName: !Sub '${DomainName}.local.'
      Comment: CNAME targeted to RDS Cluster.
      RecordSets:
        - Name: !Sub '${RDSCLUSTER}-reader.${DomainName}.local.'
          Type: CNAME
          TTL: '900'
          ResourceRecords:
            - !GetAtt 'RDSCLUSTER.ReadEndpoint.Address'

###############################################################################
Outputs:
###############################################################################
  RDSClusterIdentifier:
    Description: "RDS cluster identifier"
    Value: !Ref RDSCLUSTER
    Export:
      Name: !Sub '${AWS::StackName}-RDSClusterIdentifier'

  RDSClusterEndPointWriter:
    Description: "RDS cluster endpoint writer"
    Value: !GetAtt 'RDSCLUSTER.Endpoint.Address'
    Export:
      Name: !Sub '${AWS::StackName}-RDSClusterWriterDNSName'

  RDSClusterEndPointReader:
    Description: "RDS cluster endpoint reader"
    Value: !GetAtt 'RDSCLUSTER.ReadEndpoint.Address'
    Export:
      Name: !Sub '${AWS::StackName}-RDSClusterReaderDNSName'

  RDSSubnetGroupName:
    Description: "RDS subnet group name"
    Value: !Ref RDSSUBNETGROUP
    Export:
      Name: !Sub '${AWS::StackName}-RDSSubnetGroupName'
